plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  exclude:
    - src
include:
  - README.md
  - documentation/pestpp_users_manual.md
  - documentation/cmake.md
theme: jekyll-theme-midnight